# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec882abb9c9b8c3fd1daaf07eb9dc034cf8af6719dcd3f54da611dc28548a2e5df309fbd886e88260a3938a489fa30941f88caef8c4f0acacac10b9a26d77027

test:
  secret_key_base: 139b53eec734959d4838efb689544081b1b8cf612d8a0db71ca174a973cd0de6fd42f91e0bc44da76a4a48067db57efeefa25329a16e143c0de2c37ab9732647

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
